config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'

  resources :workshops, only: [:index, :show, :update] do
    
    member do
      get :instructions
      post :mark_as_done, to: "workshops#mark_as_done"
    end

    resources :posts, only: [:new, :create]
    resources :reviews, only: [:new, :create, :index]
    
  end
 
  resources :posts, only: [:index]

  resources :subscriptions, only: [:index, :new, :create, :show] do
    resources :orders, only: [:new, :create]
  end

  get "profile", to: "subscriptions#profile", as: :profile

  get 'faqs', to: "pages#faqs", as: :faqs
  get 'terms_and_conditions', to: "pages#terms_and_conditions", as: :terms_and_conditions


  resources :orders, only: [:show] do
    resources :payments, only: :new
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end


# create custom route with custom controller and custom action
# get "dashboard", to: "dashboard#index", as: :dashboard

app/models/workshop.rb
class Workshop < ApplicationRecord
  belongs_to :user
  has_many :subscription_workshops
  has_many :steps
  has_rich_text :workshop_content
  has_one_attached :photo
  has_one_attached :pdf
  has_many :posts
  has_many :reviews
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :show, :index ]

  def index
    @workshops = policy_scope(Workshop).order(created_at: :desc)
  end

  def show
    @workshop = Workshop.find(params[:id])
    authorize @workshop
  end

  def update
    @workshop = Workshop.find(params[:id])
    authorize @workshop
    @workshop.update(workshop_content_params)
    @workshop.save
  end

  def instructions
    @workshop = Workshop.find(params[:id])
    authorize @workshop
  end

  def mark_as_done
    @step = UserStep.where(:user_id => current_user.id, :step_id => params[:step_id])[0]
    @step.done = true
    @step.save
    authorize @step
  end

  private

  def workshop_content_params
    params.require(:workshop).permit(:workshop_content, :pdf)
  end
end

app/views/workshops/index.html.erb
<div id="workshop-index-banner">
  <div>
    <img src="https://res.cloudinary.com/yileijiang/image/upload/v1606228589/ateliers%20celine/workshop_index_zuibmj.jpg" alt="BEA BONAFINI">
  </div>
  <div id="workshop-index-yellow-shape">
  </div>
  <div id="workshop-index-title">
    <h1>
      Abstract Painting <br>
      Atelier <br>
      BEA BONAFINI
    </h1>
    <br>
    <div class="rectangle"> </div>
    <br>
    <br>
    <h4>Discover Bea Bonafini painting techniques to transform your home in a contemporary exhibition</h4>
    <%= link_to "Join Now", subscriptions_path, class: "button-pink" %>
  </div>
</div>

<div class="container">
  <h1>Choose Your Atelier</h1>
  <br>
  <div class="rectangle">
  </div>
  <h4>Categories:</h4>
  <div id="workshop-index-categories">
    <div class="workshop-index-category">
      <i class="fas fa-circle red-ball"></i>
      <h5>TRADITIONAL</h5>
    </div>
      <div class="workshop-index-category">
        <i class="fas fa-circle blue-ball"></i>
      <h5>FUNCTIONAL</h5>
    </div>
      <div class="workshop-index-category">
        <i class="fas fa-circle yellow-ball"></i>
      <h5>DISRUPTIVE</h5>
    </div>
      <div class="workshop-index-category">
        <i class="fas fa-circle lightblue-ball"></i>
      <h5>CONTEMPORARY</h5>
    </div>
    </div>
</div>

<div class="center">
  <div class="index-cards">
    <% @workshops.each do |workshop| %>
      <% background_url = cl_image_path workshop.photo.key, width: 300, height: 400, crop: :fill %>
        <div class="test">
          <div class="index-card" style="background-image: url('<%= background_url %>')">
          </div>
          <p> <strong><%= workshop.name %></strong> </p>
          <p><%= workshop.artist_name %></p>
          <p style="font-size: 15px; color: #455CC7; font-weight: bold;"><%= workshop.category.upcase %></p>
          <%= link_to "Discover", workshop_path(workshop), class: "button-minimal-thicker" %>
        </div>
    <% end %>
  </div>
</div>

app/views/workshops/instructions.html.erb
<div class="instructions-box">
  <div class="instructions-banner" id="test">
    <div>
      <h1><%= @workshop.name%></h1>
      <h2>Atelier</h2>
      <img class="blue-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/lqztsqrpdeth0ncdjkk6.png" alt="">
      <h3><%= @workshop.artist_name  %></h3>
      <p>You will learn the ancient technique of Cyanotype from our creative master Dimi and Yuko.</p>
      <%= link_to "Leave a Review", new_workshop_review_path(@workshop), class: "subscription-btn margin-left" %>
    </div>
    <div class="instructions-image">
      <div>
        <img src="https://images.unsplash.com/photo-1529066792305-5e4efa40fde9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80" alt="">
      </div>
      <div >
        <img src="https://images.unsplash.com/photo-1486413869840-a99ac0a4c031?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=742&q=80" alt="">
      </div>
    </div>
  </div>

  <div class="center flex-it">
    <div class="workshop-discription">
      <div class="workshop-content-left">
        <h4>What you will Learn?</h4>
        <img class="red-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
        <div>
          In this workshop, you will learn how to make cyanotype emulsion and make cyanotype prints at home. and then change the colour with tea extract.
          Our creative journey goes along with the poem by a Japanese haiku poet, Yosa Buson.
          Shining on the sea
          dazzling sunlight shaking over
          hills of flower-bloom
        </div>
      </div>
      <div class="duration-level-bar align-items-center">
        <div>
          <div class="flex-it">
            <i class="far fa-clock"></i>
            <p>4 hours of atelier</p>
          </div>
          <div class="flex-it">
            <i class="far fa-calendar-alt"></i>
            <p>12/2020</p>
          </div>
         <div class="flex-it">
            <i class="fas fa-signal"></i>
            <p>intermediate level</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="progress-bar-title">
    <h1> Workshop Progression </h1>
  </div>
  <div class="center-progress-bar">
    <div class="progress">
      <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
      </div>
  </div>
  </div>

  <div class="center-legend-bar">
    <div class="progress-bar-legend">
      <p>0%</p>
      <p>50%</p>
      <p>100%</p>
    </div>
  </div>

  <div class="center mid">
    <% counter = 1 %>
    <div class="workshop-discription">
      <div class="workshop-content-left">
        <div>
          <% @workshop.steps.each do |step| %>
            <div class="instruction-single-box">
              <div class="instructions-title" data-step= "<%=step.id%>" id="step-<%=step.id%>" >
                <h4> <%= counter %>. <%= step.title %> </h4>
              </div>

              <div class="move-videos-right">
                <div class="instructions-description">
                  <p><%= step.description %></p>
                  <div class="progress-button">
                    <%= link_to "Step completed", mark_as_done_workshop_path(:step_id => step.id), method: :post, class: "button-minimal-thicker timeline-button", data: {step: "#{step.id}"} %>
                  </div>
                </div>
                <div class="instruction-video">
                  <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= step.youtube_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
              </div>
            </div>
            <% counter += 1 %>
            <hr>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div id="community-section" class="banner-blue move-up">
    <div>
      <h1>Share Your Work on</h1>
      <h1 id="subline-post">#WeAreCéline</h1>
      <img class="blue-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
    </div>
    <div class="community-cards center">
      <% @workshop.posts.limit(6).each do |post|%>
        <% if post.photo.attached? %>
          <% background_url = cl_image_path post.photo.key, width: 300, height: 400, crop: :fill %>
        <% else %>
          <% background_url = 'https://i.redd.it/d5g2jaawgw431.jpg'%>
        <% end %>
      <div class="community-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= background_url %>')">
        <div class="community-flex-column">
          <p> <%= post.title %> </p>
          <p> <%= post.user.username %> </p>
        </div>
      </div>
      <% end %>
    </div>
    <%= link_to "Share your Work",  new_workshop_post_path(@workshop), class: "button-social" %>
  </div>
</div>

app/views/workshops/show.html.erb
<% content_for :meta_title, "#{@workshop.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @workshop.workshop_description %>
<% content_for :meta_image, cl_image_path(@workshop.photo.key) %>

<div class="banner-small">
  <div>
    <h1><%= @workshop.name%></h1>
    <h2>Atelier</h2>
    <img class="blue-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/lqztsqrpdeth0ncdjkk6.png" alt="">
    <h3><%= @workshop.artist_name  %></h3>
    <p>You will explore the ancient technique of Cyanotype re-interpreted by our creative master Dimi and Yuko.</p>
    <%= link_to "Join Now", subscriptions_path, class: "button-show-blue"%>
  </div>
  <div class="show-image">
    <div>
      <img src="https://images.unsplash.com/photo-1529066792305-5e4efa40fde9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80" alt="">
    </div>
    <div >
      <img src="https://images.unsplash.com/photo-1486413869840-a99ac0a4c031?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=742&q=80" alt="">
    </div>
  </div>
</div>

<div class="center">
  <div>
    <div class="bulletins">
      <a href="#create-section">Ateliers <br> Experience</a>
      <a href="#technique-section">Artists <br> & Technique </a>
      <a href="#community-section">Commuinty <br> Info</a>
    </div>
  </div>
  <div class="workshop-box">
    <div>
      <img class="imgage-discription" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232606/atelier-celine/Landing%20Page/iscwi7batxkd5vgly5f7.png" alt="">
    </div>
    <div id="create-section" class="workshop-content-right">
      <h4>What you will create?</h4>
      <img class="red-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
      <p>
        Dimi & Yuko have designed a unique workshop in which the poem of  a famous Japanese poet Buson Yosa comes to life. Throughout the atelier, you will explore the ancient technique of Cyanotype and  travel across the Japanese literature with our creative master Dimi and Yuko.
      </p>
    </div>
  </div>

  <div class="workshop-discription">
    <div id="technique-section" class="workshop-content-left">
      <h4>Origins of the Cyanotype</h4>
      <img class="red-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
      <p>
        Cyanotype is a 170 year old photographic printing process that produces prints in a distinctive dark greenish-blue. The word cyan comes from the Greek, meaning  “dark blue substance.”
        The process was invented by Sir John Herschel, a brilliant astronomer and scientist, in 1842.
        However, Herschel did not use cyanotype for photography, but for reproducing notes. It was a family friend, the botanist Anna Atkins, who used the cyanotype printing process in 1843 to create an album of algae specimens. She created the images by placing objects directly on photosensitive paper. She is regarded as the first female photographer.
      </p>
    </div>
    <img class="imgage-discription" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606231590/atelier-celine/Landing%20Page/db6de1q8gpxlvymrmr97.jpg" alt="">
  </div>

  <div class="workshop-discription">
    <img class="imgage-discription" src="https://images.unsplash.com/photo-1595523052653-b9f497845c3d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" alt="">
    <div class="workshop-content-right">
      <h4>About the artist</h4>
      <img class="red-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
      <p>
        DIMI // GREECE
        Dimitri is a visual artist based in Kreuzberg  (Berlin) working in the fields of photography and printing. During his studies in fine arts department in Kunstuniversität Linz, Austria, his interest in analogue photography and the interaction with painting was arising.
      </p>
      <p>
        YUKO // JAPAN
        After working with publishers and gaming companies for 5 years, Yukos career shifted to beeing a visual artist in Berlin. For her Cyanotype is a great way to transform a digital image into real life. Yuko is excited to share her knowledge about digital negatives and the science behind cyanotype with you.
      </p>
    </div>
  </div>

  <div class="workshop-discription">
  <div class="workshop-content-left">
    <h4>Included in the experience</h4>
    <img class="red-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
  </div>
  </div>

  <div class="experience-icons">
    <div class="center-icon-experience">
      <i class="fas fa-play"></i>
      <p> PRE- RECORDED <br> VIDEO TUTORIAL <br> WITH DIMI & YUKO </p>
    </div>
    <div class="center-icon-experience">
      <i class="fas fa-plus"></i>
    </div>
    <div class="center-icon-experience">
      <i class="fas fa-box"></i>
      <p> PHYSICAL KIT DELIVERED TO <br> YOUR HOME WITH THE <br> SUPPLIES FOR ONE CRAFT</p>
    </div>
    <div class="center-icon-experience">
      <i class="fas fa-plus"></i>
    </div>
    <div class="center-icon-experience">
      <i class="fas fa-chalkboard-teacher"></i>
      <p> LIVE Q&A <br> SESSION WITH <br> THE ARTIST</p>
    </div>
  </div>

  <div class="workshop-discription">
    <div class="workshop-content-left">
      <h4>Physical Kit </h4>
      <img class="red-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
    </div>
  </div>
  <div>
    <img src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606303051/atelier-celine/Landing%20Page/r4lthucxkl9pjztl1y2i.png" alt="Art Kit Content">
    <img id="kit-image" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606304140/atelier-celine/Landing%20Page/hmeuk5ndwch1k2dtr1sp.png" alt="Art Kit">
  </div>
  <div class="button-show-bottom">
    <%= link_to "Join Now", subscriptions_path, class: "button-show"%>
  </div>
</div> <!-- delete but center tag -->

<div id="community-section" class="banner-blue">
  <div>
    <h1>Community</h1>
    <h1 id="subline-post">#WeAreCéline</h1>
    <img class="blue-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
  </div>
  <div class="community-cards center">
    <% @workshop.posts.reverse.first(6).each do |post|%>
      <% if post.photo.attached? %>
        <% background_url = cl_image_path post.photo.key, width: 300, height: 400, crop: :fill %>
      <% else %>
        <% background_url = 'https://i.redd.it/d5g2jaawgw431.jpg'%>
      <% end %>
      <div class="community-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= background_url %>')">
        <div class="community-flex-column">
          <p> <%= post.title %> </p>
          <p> <%= post.user.username %> </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="center">
  <div class="headline-box">
    <div id="reviews_all">
      <h4>What Crafters think? </h4>
      <img class="red-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
    </div>
    <div class="reviews">
      <% @workshop.reviews.reverse.first(3).each do |review|%>
      <div class="review">
        <% case review.rating %>
          <%when 1%>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
          <%when 2%>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
          <%when 3%>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
          <%when 4%>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
          <%when 5%>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
          <%else%>
            <%= "Rating must be between 1 and 5 Stars"%>
          <%end%>
      <p> <%= review.comment %></p>
      <p class="review-username"> <%= review.user.username %></p>
      </div>
      <% end %>
    </div>
  </div>
</div>