config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'

  resources :workshops, only: [:index, :show, :update] do
    
    member do
      get :instructions
      post :mark_as_done, to: "workshops#mark_as_done"
    end

    resources :posts, only: [:new, :create]
    resources :reviews, only: [:new, :create, :index]
    
  end
 
  resources :posts, only: [:index]

  resources :subscriptions, only: [:index, :new, :create, :show] do
    resources :orders, only: [:new, :create]
  end

  get "profile", to: "subscriptions#profile", as: :profile

  get 'faqs', to: "pages#faqs", as: :faqs
  get 'terms_and_conditions', to: "pages#terms_and_conditions", as: :terms_and_conditions


  resources :orders, only: [:show] do
    resources :payments, only: :new
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end


# create custom route with custom controller and custom action
# get "dashboard", to: "dashboard#index", as: :dashboard

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :subscription
  monetize :amount_cents
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :workshop
  has_one_attached :photo
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :workshop
  validates :rating, :comment, presence: true
  validates :rating, inclusion: { in: 1..5 }
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :workshop
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  has_many :subscription_workshops
  has_many :workshops, through: :subscription_workshops
  has_many :reviews
  monetize :price_cents
end

app/models/subscription_workshop.rb
class SubscriptionWorkshop < ApplicationRecord
  belongs_to :subscription
  belongs_to :workshop
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subscriptions
  has_many :workshops
  has_many :orders
  has_one_attached :photo
  has_many :user_steps
  has_many :steps, through: :user_steps
  has_many :posts
  has_many :reviews
  # validates :username, :first_name, :last_name, :country, :city, :state, :postcode, :street, presence: true
  # validates :username, uniqueness: true
  # validates_format_of :country, :city, :state, with: /\D+/i
  # TODO: validation of phone number with regex. Look up in excercise @Michael
end

app/models/user_step.rb
class UserStep < ApplicationRecord
  belongs_to :user
  belongs_to :step
end

app/models/workshop.rb
class Workshop < ApplicationRecord
  belongs_to :user
  has_many :subscription_workshops
  has_many :steps
  has_rich_text :workshop_content
  has_one_attached :photo
  has_one_attached :pdf
  has_many :posts
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :last_name, :first_name, :country, :city, :state, :postcode, :phone, :street, :bio, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :current_password, :bio, :photo])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
    authorize self
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :skip_authorization

  def new
    subscription = Subscription.find(params[:subscription_id])
    order = Order.create!(subscription: subscription, subscription_sku: subscription.sku, amount: subscription.price, state: 'pending', user: current_user)

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: subscription.sku,
        amount: subscription.price_cents,
        currency: 'eur',
        quantity: 1
      }],
      success_url: order_url(order),
      cancel_url: order_url(order)
    )

    order.update(checkout_session_id: session.id)
    redirect_to new_order_payment_path(order)
  end

  def show
    @order = current_user.orders.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :faq, :terms_and_conditions ]

  def home
  end

  def faqs
  end

  def terms_and_conditions
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :skip_authorization

  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
    @user = current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    @workshop = Workshop.find(params[:workshop_id])
    @post.workshop = @workshop
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @workshop = Workshop.find(params[:workshop_id])
    authorize @post
    @post.user = current_user
    @post.workshop = @workshop
    if @post.save
      # redirect_to workshop_path(@workshop, anchor: "posts_all")
      redirect_to posts_path(anchor: "posts_all")
    else
      render :new
    end
  end

  def index
    @posts = policy_scope(Post).order(created_at: :desc)
  end

  private

  def post_params
    params.require(:post).permit(:title, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @workshop = Workshop.find(params[:workshop_id])
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @workshop = Workshop.find(params[:workshop_id])
    authorize @review
    @review.user = current_user
    @review.workshop = @workshop
    if @review.save
      redirect_to workshop_path(@workshop, anchor: "reviews_all")
    else
      render :new
    end
  end

  def index
    @reviews = policy_scope(Review).order(created_at: :asc)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :show, :index ]

  def index
    @workshops = policy_scope(Workshop).order(created_at: :desc)
  end

  def show
    @workshop = Workshop.find(params[:id])
    authorize @workshop
  end

  def update
    @workshop = Workshop.find(params[:id])
    authorize @workshop
    @workshop.update(workshop_content_params)
    @workshop.save
  end

  def instructions
    @workshop = Workshop.find(params[:id])
    authorize @workshop
  end

  def mark_as_done
    @step = UserStep.where(:user_id => current_user.id, :step_id => params[:step_id])[0]
    @step.done = true
    @step.save
    authorize @step
  end

  private

  def workshop_content_params
    params.require(:workshop).permit(:workshop_content, :pdf)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ateliers Celine - Ateliers Celine has curated workshop experiences led by expert artisan makers to nourish the creative soul. Our Artisan Workshops Kits.</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--Added Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--     favicon added-->
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
  </head>
  <body>
    <div class="page-container">
      <div class="navbar-container">
        <%= render "shared/navbar" %>
      </div>
      <div class="content-container">
        <%= yield %>
        <%=  render 'shared/flashes' %>
      </div>
      <div class="footer-container">
        <%= render "shared/footer" %>
      </div>
    </div>
  </body>
</html>

app/views/pages/faqs.html.erb
<div class="container">
  <h1>Frequently Asked Questions</h1>
  <br>
  <div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
        1. How Does It Work?</a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse in">
      <div class="panel-body">Hi! Welcome. We’ve built this membership community to be a slow crafting reminder of how important it is to feed our creative spirits. This project is also meant as a sustainable solution to support artists, small family businesses and our quality manufacturers by providing them with advanced lead times through a monthly subscription model.We offer Memberships (either monthly, 3-month, or 6-month subscriptions) and our Marketplace (with past workshops, add-on kits, extra materials, and our premium workshops). By joining our subscription, you’re opting into a monthly, curated craft project and to learn a new artistic style, to fully build out your crafting toolbox, and to explore your own personal creative boundaries!As a monthly member, you can always pause, reactivate, skip, swap, or cancel your subscription within your account. Please note that your payment information will be charged at the time of signing up and then again on the 15th of the month after that. Please note: 3-month or 6-month subscriptions are offered at a discounted rate because you will not have the option to skip.We've built our projects with an 18+ audience in mind - kits can contain sharp tools and dangerous materials. See our terms & conditions for more information.</div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
        2. How Do I access My Video Workshop?</a>
      </h4>
    </div>
    <div id="collapse2" class="panel-collapse collapse">
      <div class="panel-body">Looking for a beautiful instructional video to teach you a new craft? Who could blame you! Just follow these steps:Log in to your Account > Navigate to Workshop Gallery > Scroll to Video > Craft! Membership: If you are a member and receive the monthly Featured Makers kits, the tutorial video would appear in the Workshop Galley of your Account Dashboard on the 1st of the month. Your videos can always be located here and will never expire! You get to experience the thoughtfully crafted process as long as you would like. Pro-tip: you might have to scroll to locate your video! If you do not see the video in your Workshop Gallery, please be sure to reach out to us at hello@ateliersceline.com - we are happy to help! Our wonderful customer service team is available 7 days a week to help you with any account questions. Marketplace: When purchasing a full kit or video-access from The Crafter's Box Marketplace, the tutorial should appear in your account right away. Please refresh the page if you still do not see it or reach out to our Customer Experience Team.</div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
        3. Shipping Information and Timelines</a>
      </h4>
    </div>
    <div id="collapse3" class="panel-collapse collapse">
      <div class="panel-body">Marketplace Purchase: Our hardworking team works hard to make sure orders are assembled and shipped as soon as possible! It can vary based on the items in your order, the time of day you placed your order, and our current stock levels. Our team aims to assemble, package, and ship your order within 3 business days of it being placed. Shipping and arrival may be affected by inventory, observed holidays or carrier peak periods. Please note: Our Premium Workshops and larger items often include many items, therefore have an extended timeline for shipping. Please reach out to us for an exact timeline, our team will be happy to provide you with a quote based on your exact order. Once your package is shipped, you’ll be emailed with tracking details  and your order should arrive in 3-7 business days. Subscription Orders: We kit and ship all subscription boxes at the same time each month. We aim for all subscription boxes to ship the first full week of the month.</div>
    </div>
  </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse4">
        4. I Am Missing An Item</a>
      </h4>
    </div>
    <div id="collapse4" class="panel-collapse collapse">
      <div class="panel-body">Oh no! We will ship you out whatever items may have accidentally not made it in to your box asap. Just send us an email to hello@ateliersceline.com. We are so sorry for the inconvenience and we would love to make it right right away.
    </div>
    </div>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<div class="video-box">
  <video playsinline autoplay muted loop  id="bgvid">
    <source src="https://res.cloudinary.com/dxdboxbyb/video/upload/v1606230606/atelier-celine/Landing%20Page/InVideo___JOB_ID__2412485pprenderfs_1605276200142_jjrdtp.mp4" type="video/mp4">
  </video>
  <div class="gradient">
  </div>
  <div class="overlay banner">
    <h1>Inspired by Traditions,<br>Crafted by you </h1>
    <%= link_to "Discover new Art", workshops_path, class: "button-pink"%>
  </div>
</div>

<div class="center">
  <div class="workshop-discription">
    <div class="workshop-content-left">
      <h5> Kits & Digital <br> Workshops For The <br> Creative Hobbys </h5>
      <img class="red-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
      <p class="landing-page-text">
      Ateliers Céline is a monthly Do It Yourself experience for people who love to make, build, shape, design, and create! Each box includes supplies for one craft creation as well as access to online instructions by the featured artist of the month
      </p>
    </div>
    <img id="landing-image-kit" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606231624/atelier-celine/Landing%20Page/lwsvy6fnq7cmh4nrf3n2.png" alt="Art Kit">
  </div>
</div>

<div class="center">
  <div id="finger-print-box">
    <div class="workshop-content-left">
      <h4> How Does It Work? </h4>
      <img class="red-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
    </div >
    <img id="landing-image-print" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606398509/atelier-celine/Landing%20Page/ihbhnddwairdal53ilxb.png" alt="Art Kit">
  </div>
</div>

<div id="carousel-container">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active ">
        <div class="carousel-card">
          <div class="text-left">
            <h1>Become Part of a Community</h1> <br>
            <p>Our goal is to support hobbyist crafters, artists, and quality manufacturers while building a community focused on handmade and preserving traditional art techniques</p>
          </div>
          <div class="text-right">
            <img src="https://res.cloudinary.com/yileijiang/image/upload/v1606770443/59652_f8ryku.png" alt="share">
            <p>Get inspired and inspire others</p>
          </div>
        </div>
        <%# <div class="filter"> </div> %>
        <img class="d-block w-100" src="https://res.cloudinary.com/yileijiang/image/upload/v1606845211/creativity-2735435_1920_cfu1l9.jpg" alt="First slide">
      </div>
      <div class="carousel-item">
        <div class="carousel-card">
          <div class="text-left">
            <h1>Stay Continuously Engaged </h1> <br>
            <p>Each month, we will introduce a new atelier combining a physical toolkit and digital instructions, to encourage the continuous discovery of new artists and techniques</p>
          </div>
          <div class="text-right">
            <img src="https://res.cloudinary.com/yileijiang/image/upload/v1606845664/noun_Speech_Bubble_1676263_z2gqpo.png" alt="share">
            <p>Never loose inspiration</p>
          </div>
        </div>
        <%# <div class="filter"> </div> %>
        <img class="d-block w-100" src="https://res.cloudinary.com/yileijiang/image/upload/v1606845211/drawing-1209629_1920_jyzot5.jpg" alt="Second slide">
      </div>
      <div class="carousel-item">
        <div class="carousel-card">
          <div class="text-left">
            <h1>Engage Directly With Our Artists</h1> <br>
            <p>Ateliers Céline is disrupting the traditional arts & crafts retail industry by offering curated digital workshops with shipped kits of high-end tools & materials for convenient at home making</p>
          </div>
          <div class="text-right">
            <img src="https://res.cloudinary.com/yileijiang/image/upload/v1606845664/noun_Video_Camera_1019270_ajelis.png" alt="share">
            <p>Polish your craft</p>
          </div>
        </div>
        <%# <div class="filter"> </div> %>
        <img class="d-block w-100" src="https://res.cloudinary.com/yileijiang/image/upload/v1606845106/leather-craft-3787282_1920_a1uj8q.jpg" alt="Third slide">
      </div>
       <div class="carousel-item">
          <div class="carousel-card">
            <div class="text-left">
              <h1>Create From The Comfort Of Your Home</h1> <br>
              <p>Ateliers Céline is disrupting the traditional arts & crafts retail industry by offering curated digital workshops with shipped kits of high-end tools & materials for convenient at home making</p>
            </div>
            <div class="text-right">
              <img src="https://res.cloudinary.com/yileijiang/image/upload/v1606845664/4c17728f464a24d678f6d947e16a8df6-gift-box-hand-drawn-icon-53-by-vexels_yqheob.png" alt="share">
              <p>Make your home a creative space</p>
            </div>
          </div>
        <%# <div class="filter"> </div> %>
          <img class="d-block w-100" src="https://res.cloudinary.com/yileijiang/image/upload/v1606845080/weaving-loom-2571179_1920_apm9ib.jpg" alt="Fourth slide">
        </div>
    </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
      </a>
  </div>
</div>

<div class="center">
  <div class="workshop-discription">
    <div class="workshop-content-left">
      <h4> Sneak Peek Into Our User’s Creations </h4>
      <img class="red-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
    </div>
  </div>

  <div class="home-cards">
    <div class="home-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1593806967876-4ad6cd0c5759?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=895&q=80)">
      <p>Lilli</p>
      <i class="fas fa-heart"></i>
    </div>
    <div class="home-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1560719268-60a714bd4c31?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80)">
      <p>James</p>
      <i class="fas fa-heart"></i>
    </div>
    <div class="home-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dxdboxbyb/image/upload/v1606231610/atelier-celine/Landing%20Page/b2mtb0z38mkakufor145.jpg)">
      <p>Timothy</p>
      <i class="fas fa-heart"></i>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <div class="button-bottom-home">
      <%= link_to "Discover new Art", workshops_path, class: "button-pink bigger"%>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div>
    <img src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606162936/atelier-celine/Landing%20Page/pwlvhly2kicxvqtkspql.png" alt="wave" class="footer-image-left">
  </div>
  <div class="infos">
    <strong>About us</strong>
    <ul>
      <li><%= link_to "Terms & Conditions", terms_and_conditions_path  %> </li>
    </ul>
  </div>
  <div class="infos">
    <strong>Contact us</strong>
    <ul>
      <li><%= link_to "Faqs", faqs_path %></li>
    </ul>
  </div>
  <div class="footer-links">
    <div class="infos">
      <p><strong>Follow us</strong></p>
    </div>
    <a href="https://instagram.com/ateliersceline?igshid=7dhdlyw8mrzd"><i class="fab fa-instagram" target="_blank"></i></a>
    <a href="https://www.facebook.com/WeAreCeline" target="_blank"><i class="fab fa-facebook"></i></a>
  </div>
    <img src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606162190/atelier-celine/Landing%20Page/m1jduehavakcwk3wpmm1.png" alt="wave" class="footer-image-right">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon nav-own">
<div class="test1"> 
  <div navbar-space>
    <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dxdboxbyb/image/upload/v1606156054/atelier-celine/jublitpripa5ijbpcoxt.jpg", class: "nav-img" %>
    <% end %>
  </div>
  <%= image_tag "https://res.cloudinary.com/dxdboxbyb/image/upload/v1606155677/atelier-celine/xtnumel8ux618dntifyn.jpg", class: "nav-img word-logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  </div>
  <div class="test2"> 
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Join us", subscriptions_path, class: "nav-link pad" %>
        </li>
        <li class="nav-item">
          <%= link_to "Marketplace", workshops_path, class: "nav-link pad" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Our ateliers", workshops_path, class: "nav-link pad" %>
        </li>
        <li class="nav-item">
          <%= link_to "#WeAreCéline", posts_path, class: "nav-link pad" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, :width =>100, :height => 100, class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <%else %>
            <%= image_tag "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80", class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", profile_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Our ateliers", new_user_session_path, class: "nav-link pad" %>
        </li>
        <li class="nav-item">
          <%= link_to "#WeAreCéline", new_user_session_path, class: "nav-link pad" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link pad" %>
        </li>
        <li class="nav-item button-nav">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    </div>

  </div>
</div>