config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'

  resources :workshops, only: [:index, :show, :update] do
    
    member do
      get :instructions
      post :mark_as_done, to: "workshops#mark_as_done"
    end

    resources :posts, only: [:new, :create]
    resources :reviews, only: [:new, :create, :index]
    
  end
 
  resources :posts, only: [:index]

  resources :subscriptions, only: [:index, :new, :create, :show] do
    resources :orders, only: [:new, :create]
  end

  get "profile", to: "subscriptions#profile", as: :profile

  get 'faqs', to: "pages#faqs", as: :faqs
  get 'terms_and_conditions', to: "pages#terms_and_conditions", as: :terms_and_conditions


  resources :orders, only: [:show] do
    resources :payments, only: :new
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end


# create custom route with custom controller and custom action
# get "dashboard", to: "dashboard#index", as: :dashboard

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  has_many :subscription_workshops
  has_many :workshops, through: :subscription_workshops
  has_many :reviews
  monetize :price_cents
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def index
    @subscriptions = policy_scope(Subscription).order(created_at: :desc)
    @workshops = policy_scope(Workshop).order(created_at: :desc)
    @subscription = Subscription.new()
  end

  def show
    @subscription = Subscription.find(params[:id])
    authorize @subscription
  end

  def new
    @subscription = Subscription.new
    authorize @subscription
  end

  def create
    @subscription = Subscription.new(subscription_params)
    if !@subscription.workshops.any?
      @subscription.workshops << Workshop.find(params[:subscription][:workshop_ids])
    end
    authorize @subscription
    @subscription.user = current_user
    @subscription.save
    if @subscription.workshops.count == 3
      @subscription.start_date = Date.today
      @subscription.duration = 3
      # TODO: add end_date
      @subscription.price = 185
      @subscription.sku = "Three Month Plan"

      @subscription.workshops.each do |workshop|
        workshop.steps.each do |step|
          user_step = UserStep.new
          user_step.user = current_user
          user_step.step = step
          user_step.done = false
          user_step.save
        end
      end

    else
      @subscription.start_date = Date.today
      @subscription.duration = 1
      @subscription.price = 90
      @subscription.sku = "One Month Plan"

      user_step = UserStep.new
      user_step.user = current_user
      @subscription.workshops[0].steps.each do |step|
        user_step = UserStep.new
        user_step.user = current_user
        user_step.step = step
        user_step.done = false
        user_step.save
      end
    end
    @subscription.save
    redirect_to new_subscription_order_path(@subscription)
  end

  def profile
    @user = current_user
    @subscription = @user.subscriptions
    @usersteps = @user.user_steps
    @usersteps_done = []

    @usersteps.each do |userstep|
      if userstep.done == true
        @usersteps_done << userstep
      end
    end
    authorize @subscription
    @workshops = @user.subscriptions[0].workshops if !@user.subscriptions.empty?
  end

  private

  def subscription_params
    params.require(:subscription).permit(:start_date, :end_date, :duration, :price, :name, :sku, workshop_ids: [])
  end
end

app/views/subscriptions/create.html.erb
<h1>Subscriptions#create</h1>
<p>Find me in app/views/subscriptions/create.html.erb</p>

app/views/subscriptions/index.html.erb
<div class="subscription-banner">
  <div class="subscription-title">
    <h1>Choose your Plan</h1>
    <img class="blue-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/lqztsqrpdeth0ncdjkk6.png" alt="">
    <h3>Select from our <br> two possible plans</h3>
  </div>
  <img src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606331324/atelier-celine/Landing%20Page/bviz0syo2xx7bfbdw4r7.png" alt="wave symbol">
  <div class="subscription-cards">
    <div class="subscription-card" id="subscription-card-one">
      <h2>One Month</h2>
      <p class="price">90$</p>
      <ul>
        <li><i class="fas fa-check"></i> A digital workshop </li>
        <li><i class="fas fa-check"></i> A shipped kit of handmade tools & materials</li>
        <li><i class="fas fa-check"></i> A monthly Q&A with maker </li>
      </ul>
      <a href="#" id="one_month" class="subscription-btn">Select</a>
    </div>
    <div class="subscription-card" id="subscription-card-three">
      <h2>Three Month </h2>
      <p class="price">185$</p>
      <ul>
        <li><i class="fas fa-check"></i> Three digital workshops </li>
        <li><i class="fas fa-check"></i> Three shipped kits of handmade tools & materials</li>
        <li><i class="fas fa-check"></i> A monthly Q&A with maker </li>
      </ul>
          <a href="#" class="subscription-btn" id="three_months">Select</a>
    </div>
  </div>
</div>

<div class="center">
  <div class="workshop-discription">
    <div class="workshop-content-left">
      <h4>Select your Atelier</h4>
      <img class="red-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
    </div>
  </div>
</div>

<div class="selector-cards" >
  <%= simple_form_for(@subscription) do |f| %>
      <%= f.association :workshops,
                  as: :check_boxes,legend_tag: false,
                  :label_method => lambda { |workshop|
                  "<div>
                    #{cl_image_tag(workshop.photo.key, width: 320, height: 280, :radius=>10)}
                    <p><strong>#{workshop.name}</strong></p>
                    <p>#{workshop.artist_name}</p>
                    <h4>#{workshop.category}</h4>
                  </div>".html_safe
                  },
                  # label_method: ->(workshop){"#{workshop.photo.key}"},
                  #as: :radio_buttons,legend_tag: false,
                  input_html: { class: "tag-selector workshop" },
                  item_wrapper_class: 'tag-item' %>
  <%= f.button :submit,"Confirm Selection", class: "button-blue" %>
  <% end %>
</div>

app/views/subscriptions/new.html.erb
<h1>Subscriptions#new</h1>
<p>Find me in app/views/subscriptions/new.html.erb</p>

app/views/subscriptions/profile.html.erb
<div id="profile-banner">
  <div class="container-profile">
    <h1> My Profile </h1>
    <br>
    <div class="rectangle">
    </div>
    <div id="profile">
      <div id="profile-picture">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key %>
        <%else %>
          <%= image_tag "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80" %>
        <% end %>
      </div>
      <div id="profile-description">
        <h5> <%= @user.username %></h5>
        <div id="profile-address">
          <i class="fas fa-user"> </i> <%= @user.first_name %> <%= @user.last_name %> <br>
          <i class="fas fa-envelope"> </i> <%= @user.email %> <br>
          <i class="fas fa-map-marker-alt"></i> <%= @user.street %>, <%= @user.postcode %> <%= @user.city %>
        </div>
        <br>
        <% if @user.bio == "" || @user.bio==nil %>
          <p>Nothing here yet. Please update your bio.</p>
        <% else %>
          <p id="bio"> <%= @user.bio %> </p>
        <% end %>
      </div>
    </div>
    <%= link_to "Edit", edit_user_registration_path, class: "button-pink" %>
  </div>
</div>

<div class="container">
  <h1> My Ateliers</h1>
  <br>
  <div class="rectangle">
  </div>
  <div class="my-workshops">
    <div class="center-profile">
      <div class="index-cards">
        <% if @workshops.nil? == false %>
          <% @workshops.each do |workshop| %>
          <% background_url = cl_image_path workshop.photo.key, width: 300, height: 400, crop: :fill %>
            <div class="test">
              <div class="index-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= background_url %>')">
              </div>
              <p> <strong><%= workshop.name %> </strong> </p>
              <p> <%= @usersteps_done.length %>/<%= @usersteps.length %> steps completed </p>
              <p><%= workshop.artist_name %></p>
              <p style="font-size: 15px; color: #455CC7; font-weight: bold;"><%= workshop.category.upcase %></p>
              <p> <%= link_to "Instructions", instructions_workshop_path(workshop), class: "button-minimal-thicker" %></p>
              <p> <%= link_to "Leave a Review", new_workshop_review_path(workshop), class: "button-minimal-thicker-subscription" %></p>
            </div>
          <% end %>
          <% else %>
            <p> You don't have any Ateliers yet. </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/subscriptions/show.html.erb
<div class="center">
  <div class="center-child">
    <div class="workshop-discription">
      <div class="workshop-content-left">
        <h4>Almost there!</h4>
        <img class="red-line" src="https://res.cloudinary.com/dxdboxbyb/image/upload/v1606232604/atelier-celine/Landing%20Page/cluepznhimc95jwz0ono.png" alt="">
        <% @subscription.workshops %>
        <p>Awesome things are lying ahead of us</p>
        <%= form_tag orders_path do %>
        <%= hidden_field_tag 'subscription_id', @subscription.id %>
        <%= submit_tag 'Checkout', class: 'button-pink' %>
        <% end %>
      </div>
    </div>
  </div>
</div>